"""Added PayrollCycle and updated Payroll models

Revision ID: 29f265f54225
Revises: 429067893040
Create Date: 2026-01-12 20:01:00.255776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f265f54225'
down_revision = '429067893040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(batch_op.f('uq_departments_name'), ['name'])

    # with op.batch_alter_table('employees', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(batch_op.f('uq_employees_user_id'), ['user_id'])

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gross_salary', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tax_paid', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('nssf', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('nhif', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('housing_levy', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_payroll_cycle_id_payroll_cycles'), 'payroll_cycles', ['cycle_id'], ['id'])

    # with op.batch_alter_table('roles', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payroll_cycle_id_payroll_cycles'), type_='foreignkey')
        batch_op.drop_column('housing_levy')
        batch_op.drop_column('nhif')
        batch_op.drop_column('nssf')
        batch_op.drop_column('tax_paid')
        batch_op.drop_column('gross_salary')
        batch_op.drop_column('cycle_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_user_id'), type_='unique')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_departments_name'), type_='unique')

    # ### end Alembic commands ###
