"""Added manager_id to departments

Revision ID: 429067893040
Revises: 0b67ce8c1b7b
Create Date: 2026-01-12 14:34:45.184168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429067893040'
down_revision = '0b67ce8c1b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_departments_manager_id', 'employees', ['manager_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_departments_manager_id', type_='foreignkey')
        batch_op.drop_column('manager_id')

    # ### end Alembic commands ###
