"""patch missing schema

Revision ID: 6def12345678
Revises: 5cda93501906
Create Date: 2026-01-16 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6def12345678'
down_revision = '5cda93501906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create activity_logs table
    op.create_table('activity_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('details', sa.String(length=255), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Add employee_number to employees
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_employees_employee_number'), ['employee_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_employee_number'), type_='unique')
        batch_op.drop_column('employee_number')

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
